services:
  - type: web
    name: uhstiit-pdf-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 1 --timeout 120 run:app
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECRET_KEY
        generateValue: true
